export const MESSAGES_INVALIDATE = 'MESSAGES_INVALIDATE';
export const MESSAGES_REQUEST = 'MESSAGES_REQUEST';
export const MESSAGES_SUCCESS = 'MESSAGES_SUCCESS';
export const MESSAGES_FAILURE = 'MESSAGES_FAILURE';
export const MESSAGE_ADD_REQUEST = 'MESSAGE_ADD_REQUEST';
export const MESSAGE_ADD_SUCCESS = 'MESSAGE_ADD_SUCCESS';
export const MESSAGE_ADD_FAILURE = 'MESSAGE_ADD_FAILURE';
export const MESSAGE_DELETE_REQUEST = 'MESSAGE_DELETE_REQUEST';
export const MESSAGE_DELETE_SUCCESS = 'MESSAGE_DELETE_SUCCESS';
export const MESSAGE_DELETE_FAILURE = 'MESSAGE_DELETE_FAILURE';

export const USER_SET_USERNAME = 'USER_SET_USERNAME';
export const USER_SET_AVATAR = 'USER_SET_AVATAR';

export const ERROR_MESSAGE_RESET = 'ERROR_MESSAGE_RESET';
